# Generated by Django 4.2.3 on 2023-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheatreHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rows", models.IntegerField()),
                ("seats_in_row", models.IntegerField()),
            ],
        ),
    ]
