# Generated by Django 4.2.3 on 2023-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0005_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
