# Generated by Django 4.2.3 on 2023-07-28 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0006_ticket_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theatrehall",
            name="rows",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Theatre Hall must have at least 1 row"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="theatrehall",
            name="seats_in_row",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "There must be at least 1 seat in a row"
                    )
                ]
            ),
        ),
    ]
