# Generated by Django 4.2.3 on 2023-07-28 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0007_alter_theatrehall_rows_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theatrehall",
            name="rows",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Theatre Hall must have at least 1 row"
                    )
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "row", "performance"),
                name="unique_seat_row_performance",
            ),
        ),
    ]
