# Generated by Django 4.2.3 on 2023-07-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0008_alter_theatrehall_rows_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="theatre.reservation"
            ),
        ),
    ]
